apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.vcm.name}}-http
spec:
  selector:
    app: {{.Values.vcm.name}}
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.vcm.port }}
status:
  loadBalancer: {}