development:
  server:
    port: 8888
    url: http://localhost:8888/
    jwt:
      key: VCMKey
  mongo:
    port: 27017
    host: 192.168.99.100
    database: vcm
test:
  server:
    port: 8888
    url: http://localhost:8888/
    jwt:
      key: VCMKey
  mongo:
    port: 27017
    host: 192.168.99.100
    database: vcm
staging:
  server:
    port: 8888
    url: http://localhost:8888/
    jwt:
      key: VCMKey
  mongo:
    port: 27017
    host: 192.168.99.100
    database: vcm
production:
  server:
    port: 8888
    url: http://localhost:8888/
    jwt:
      key: VCMKey
  mongo:
    port: 27017
    host: mongo
    database: vcm
